name: Standard Build CI for master branch

on:
    push:
        branches:
            - 'master'

jobs:
  changelog_version_check:
    name: Check CHANGELOG/package version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: changelog_reader
      name: Get Changelog Entry
      uses: mindsers/changelog-reader-action@v2
      with:
        path: ./CHANGELOG.md
    - uses: mukunku/tag-exists-action@v1.0.0
      id: checkTag
      with:
        tag: 'ivicos_${{ steps.changelog_reader.outputs.version }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check newest version validity
      run: bash ./scripts/check-version.sh ${{ steps.changelog_reader.outputs.version }} ${{ steps.checkTag.outputs.exists }}
    - name: Check package version validity
      run: bash ./scripts/check-package-version.sh ${{ steps.changelog_reader.outputs.version }}
  build_lint:
    name: Building and checking linter for the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: npm run lint
  publish_package:
    name: Testing and publishing the package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm test
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
  create_release:
    name: Create tag and release 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: changelog_reader
      name: Get Changelog Entry
      uses: mindsers/changelog-reader-action@v2
      with:
        path: ./CHANGELOG.md
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/ivicos_${{ steps.changelog_reader.outputs.version }}",
            sha: context.sha
          })
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ivicos_${{ steps.changelog_reader.outputs.version }}
        tag_name: ivicos_${{ steps.changelog_reader.outputs.version }}
        body: ${{ steps.changelog_reader.outputs.changes }}
        prerelease: ${{ steps.changelog_reader.outputs.status == 'prereleased' }}
        draft: ${{ steps.changelog_reader.outputs.status == 'unreleased' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}